version: '3.8'

services:
  # 数据库服务
  mysql:
    image: mysql:8.0  # 使用官方MySQL镜像
    container_name: showroom-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: showroom_system
      MYSQL_USER: showroom
      MYSQL_PASSWORD: showroom123
    ports:
      - "3308:3306"  # MySQL 默认端口
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化SQL脚本
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 后端服务
  backend:
    image: lizao678/showroom-backend:latest
    container_name: showroom-backend
    environment:
      DB_HOST: mysql
      DB_USER: showroom
      DB_PASSWORD: showroom123
      DB_NAME: showroom_system
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_TO: ${MAIL_TO}
      PORT: 3066  # 设置容器内部端口
    ports:
      - "3066:3066"  # API 服务端口
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data: 